version: "3.8"

services:
  worker:
    name: pdf-server
    image: hc-pdf-server:latest
    ports:
      - 8101:80
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip

# docker service create --name hc-pdf-server hc-pdf-server:latest
