version: "3.4"

services:
  nginx:
    image: nginx
    container_name: pdf_n_proxy
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - 8101:80
    depends_on:
      - service1
  service1: &service_1
    container_name: pdf_n_1
    image: hc-pdf-server:latest
    restart: always
  service2:
    <<: *service_1
    container_name: pdf_n_2
  service3:
    <<: *service_1
    container_name: pdf_n_3
