services:
  worker:
    image: hc-pdf-server:latest
    networks:
      - pdf-net
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
  nginx:
    image: nginx:alpine
    networks:
      - pdf-net
    ports:
      - 8101:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

networks:
  pdf-net:
    driver: bridge

# docker service create --name pdf-server hc-pdf-server:latest
# docker service update --image hc-pdf-server:latest pdf-server
