services:
  worker:
    image: hc-pdf-server:latest
    networks:
      - pdf-net
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
  nginx:
    image: nginx:alpine
    networks:
      - pdf-net
    ports:
      - 8101:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: always
      placement:
        constraints:
          - node.role == manager  # Běží pouze na manager nodu

networks:
  pdf-net:
    driver: overlay

# docker build -t hc-pdf-server:latest .
# docker stack deploy -c docker-compose.yml pdf-stack
# docker stack deploy --detach=false -c docker-compose.yml pdf-stack
# docker service scale pdf-stack_worker=2
